import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Roboto_Mono,
  Plus_Jakarta_Sans,
} from "next/font/google";
import "./globals.css";
import Navbar from "./component/navbar";
import NavbarProductDetail from "./component/navbarProductDetail";
import Card from "./component/card";
import Footer from "./component/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jakartaSans = Plus_Jakarta_Sans({
  variable: "--plus-jakarta-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${robotoMono.variable} ${jakartaSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {/* <NavbarProductDetail /> */}
        {/* <Card /> */}
        <Footer />

        {children}
      </body>
    </html>
  );
}
